version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
      - image: circleci/node:12-browsers-legacy
        command: echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Hello
          command: echo Hey there! Var: ${MY_ENV_VAR}
      - when: 
          condition: 
            equal: [main, << pipeline.git.branch >>] 
          steps:
            - checkout
            - run:
                name: Deploy Main to Heroku
                command: |
                  git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
      - when: 
          condition: 
            not: 
              equal: [main, << pipeline.git.branch >>] 
          steps:
            - run:
                name: Say hi
                command:  echo "You got to the not-main branch step"

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - build:
          context: rawr
      - deploy
