version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - when:
          condition: 
            equal: [main, << pipeline.git.branch >>]
          steps:
            -run: echo "this is branch main!"
      - run: echo "done building."
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Main to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
            when: equal: [ main, << pipeline.git.branch >> ]
